# Generated by Django 5.2.3 on 2025-06-25 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(10)])),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
