# Generated by Django 5.2.3 on 2025-06-26 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
