# Generated by Django 5.2.3 on 2025-07-01 05:36

import common.validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(10), common.validator.verify_number]),
        ),
    ]
