# Generated by Django 5.2.3 on 2025-06-25 04:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('birthday', models.DateField()),
                ('species', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('race', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
    ]
