# Generated by Django 5.2.3 on 2025-06-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('manufacturer', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Medications_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('instructions', models.CharField()),
                ('annotation_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.annotation_appointment')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medications')),
            ],
        ),
    ]
