# Generated by Django 5.2.3 on 2025-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motive', models.CharField(max_length=250)),
                ('diagnosis', models.CharField(max_length=1000)),
            ],
        ),
    ]
