# Generated by Django 5.2.3 on 2025-07-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='diagnosis',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
