# Generated by Django 5.2.3 on 2025-07-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='diagnosis',
            field=models.CharField(null=True),
        ),
    ]
