# Generated by Django 5.2.3 on 2025-06-28 17:30

import common.validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('pets', '0001_initial'),
        ('veterinarians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pet')),
                ('surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinarians.veterinarian', validators=[common.validator.validate_surgeon])),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surgeries.surgery_type')),
            ],
        ),
        migrations.CreateModel(
            name='Surgeries_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.annotation_appointment')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgeries.surgery')),
            ],
        ),
    ]
